# Generated by Django 5.0 on 2024-02-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('Firstname', models.TextField(max_length=200)),
                ('Lastname', models.TextField(max_length=200)),
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('Comments', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'Feedback',
            },
        ),
    ]
